### ISSUE TITLE
IP v6 support

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/www#212]
Hello.

I recently happened upon the Sugar Labs website while I had only IPv6 connectivity. Unfortunately the site lacks IPv6 support and thus failed to load for me.
Is this something that could be looked into being fixed?

Thanks in advance,
Raul

(Raul Tambre)

**Comment by Anonymos-Knight** [comment]
Hey,I can sort this out

**Comment by pikurasa** [comment]
I'm not sure this is still an issue. I believe I've accessed it from locations that have only had IPv6 (MAP had only that for a while)...

**Comment by chimosky** [comment]
Yes, I just tested with ping and IPv6 works.
