### ISSUE TITLE
[Feature Request] Dark Mode Feature.

### ISSUE THREAD

**Issue by inceptionabhishek** [sugarlabs/www#395]
I think adding a dark mode in this web application is very important and necessary. I can work on this issue if anyone approves.

**Comment by chimosky** [comment]
Why do you think a dark mode is important and necessary?

**Comment by inceptionabhishek** [comment]
_Well, there are many factors some of them are :_ 

 **Reduced Eye Strain**: Dark mode uses a dark background with lighter text and graphic elements, which reduces the amount of light emitted by the screen. This can help reduce eye strain, particularly in low-light conditions, and may also reduce the risk of developing digital eye strain or computer vision syndrome.

**Improved Readability**: In some situations, such as in low-light environments, a light background with dark text can be overly bright and cause glare or reflection, making it difficult to read. Dark mode can improve readability and make text easier to read.

**User Experience**: Some people simply prefer the look of dark mode, as it can give a device a more sleek and modern appearance. It may also reduce visual clutter and distractions, which can be particularly helpful when working or studying.

**Comment by quozl** [comment]
How does a web browser communicate this user preference to the JavaScript associated with the content?

I don't think of our web site as a web application.  Are you sure you are raising this issue in the correct repository?

**Comment by quozl** [comment]
That's unfortunate.  It's one of the most pressing problems with dark mode; how to determine what the user wants without them having to do anything about it for each app.  Then how to monetise the setting and sell dark theme plush toys in embedded dark pattern ads.
