### ISSUE TITLE
Inconsistent Styling of icons

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [sugarlabs/www#396]
In the Footer section of the website, the github icon has a round shape whereas the other icons have a oval shape, maybe this was done intentionally but it looks to have a inconsistent styling. 

<img width="381" alt="Screenshot 2023-02-24 at 11 58 43 PM" src="https://user-images.githubusercontent.com/75615092/221262934-44c62c23-88c1-4c37-ac61-d6ecc5ae20fd.png">

## Steps to reproduce

1.  Clone the repo and perform necessary setup as given in readme 
2.  Run bundle exec jekyll serve --incremental;
3.  Scroll to footer section

## Describe what you expected to happen

I expected the icons to have a consistent styling and shape. It would have a better impact

**Comment by quozl** [comment]
You're wrong.  The icons are all near-perfect circles.
