### ISSUE TITLE
Feature Request for Scroll to Top button 

### ISSUE THREAD

**Issue by ABHINAV-JHA-27** [sugarlabs/www#397]
After I Opened the website and Navigated to the Footer section there was a Back to Top Button but it would be better if we could have floating action button so that user can directly scroll to top whenever he wants and not from footer section.

<img width="180" alt="Screenshot 2023-02-24 at 11 58 58 PM" src="https://user-images.githubusercontent.com/75615092/221264084-bbd3bea6-74c0-4457-ab8e-c02dbcdad853.png">

## Steps to reproduce

1.  Clone the Repo and do the necessary setup as provided in the readme.
2.  Run bundle exec jekyll serve --incremental;
3.  Navigate to Footer section

## Describe what you expected to happen
I expected to have a floating action button for Back to Top action as it would give a better user Experience.

**Comment by quozl** [comment]
Back to top buttons are rarely used, and are best placed at the bottom of the content.  I've tested the feature on https://sugarlabs.org/ just now. There's no standard for back to top buttons.  I'm fine with the way it is now, and I don't think it should be changed.

**Comment by Tusharjolly21** [comment]
i want to work on this issue. assign me this issue. I will make the neccessary changes and add the floating action button for better user experience

**Comment by quozl** [comment]
We don't assign issues.  Make a pull request if you'd like your work reviewed.

However, in this issue, it isn't clear what the consensus is for what is to be done.  I don't think a floating action button is any better than what we have already.  As I've said in other issues here, we should be focusing on content for our web site, not new buttons or style changes.

**Comment by quozl** [comment]
Not required, no consensus.
