### ISSUE TITLE
feat:Highlights the section in which user is present

### ISSUE THREAD

**Issue by harshsharma-11** [sugarlabs/www#403]
when you are at homepage and if you click any section like about ,user should able to predict that he clicked the about section of navbar.
also there is absent to hover on navbar elements
for better user experience there should be proper hovering of navbar elements and also section clicked in navbar should be highlighted

https://github.com/sugarlabs/www/assets/138685168/139c33b4-228d-4cfb-b260-07283e29658d

**Comment by harshsharma-11** [comment]
cc @chimosky 
cc @walterbender 
cc @quozol
cc @srevinsaju

**Comment by quozl** [comment]
I think it is fine the way it is.  Upgrading to the latest theme and CSS from upstream if not.  I don't want to see effort wasted on unimportant aspects of our work at Sugar Labs.  The web site gets our message across fine.  Please concentrate on Sugarizer, Sugar, Music Blocks, or another of our software repositories, if you wish to contribute to Sugar Labs,.

**Comment by harshsharma-11** [comment]
okkk fine

**Comment by chimosky** [comment]
@harshsharma-11 While I agree with what quozl is saying, this is difficult as an issue because neither of us would devote our time to fixing it as it's not a priority for us, that being said, if you have a fix then please open a PR and we'll review it. 
Looking forward to your contributions!
