### ISSUE TITLE
SSL certificate is not properly managed.

### ISSUE THREAD

**Issue by DEEPAKsingh74** [sugarlabs/www#404]
I have visited your website and seen some of the ui/ux design issues, that are just the company part. But the subdomain http://planet.sugarlabs.org/  is not https so it is just a article but it creates a sense of fright to the users so please check on that part.

**Comment by quozl** [comment]
I don't see any issue with planet.sugarlabs.org so it must have been fixed.

It is, however, quite old content and doesn't help.  I'd like to see it removed.
