### ISSUE TITLE
Logo on the website looks stretched and navbar is not properly padded

### ISSUE THREAD

**Issue by 164adityakumar** [sugarlabs/www#409]
Irregular padding : 
![image](https://github.com/sugarlabs/www/assets/98655260/4e50b4ae-c8bc-449e-a192-88005044217f)

The logo seems to be stretched in width to me , or is it due to the image?

**Comment by chimosky** [comment]
@164adityakumar Could you add images of what it looks like and what it should look like, we'll need more context.

**Comment by mrmoinshaikh** [comment]
I'm interested in working on this issue. Could someone confirm if it's available for contribution?

**Comment by chimosky** [comment]
@164adityakumar what browser and screen size are you testing with?

**Comment by chimosky** [comment]
> I'm interested in working on this issue. Could someone confirm if it's available for contribution?

Are you able to reproduce the issue?

**Comment by 164adityakumar** [comment]
> @164adityakumar what browser and screen size are you testing with? As I've tested with various screen sizes and not able to see what you see.
I'm using Brave browser 
at this point everything seems fine
![image](https://github.com/sugarlabs/www/assets/98655260/8079da6e-4d0a-4f7e-bfe8-ab0aa9e53f56)
at this breakpoint the logo deforms which continues to be the same in the laptop view in brave browser
![image](https://github.com/sugarlabs/www/assets/98655260/1e1a7164-fdbc-4c94-84a5-c10309bc17ef)


although this looks perfect in Firefox in each case . The problems occurs for browser built over chrome (same issue) just like brave

**Comment by mrmoinshaikh** [comment]
> > I'm interested in working on this issue. Could someone confirm if it's available for contribution?
> 
> Are you able to reproduce the issue?

Yes, I am able to reproduce the issue on mobile device screen size logo is not aligned properly to navigation bar, I didn't found logo deformation(I am using chrome) 
![logo problem](https://github.com/sugarlabs/www/assets/138794527/590afdc8-3d70-42ad-9b70-8c18cc2ff8d3)
Here is the padding alignment issue 
![nav problem](https://github.com/sugarlabs/www/assets/138794527/8fc28e77-f594-4458-ae21-2425eddb0249)

**Comment by quozl** [comment]
Both the stretch and the alignment are intentional, and I'm fine with them.
