### ISSUE TITLE
Feat: Update Gem File 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [sugarlabs/www#411]
Currently `Gemfile` consists of some old dependencies that need to be updated so the contributor doesn't face any problems while running the website in the local server.

**Comment by DhairyaMajmudar** [comment]
@pikurasa @walterbender I faced this issue while running the website in local serve which can be solved by updating the gemfiles.

**Comment by quozl** [comment]
What was the problem you experienced?  Gemfile lists github-pages group jekyll_plugins and webrick.  Gemfile.lock lists more.

**Comment by DhairyaMajmudar** [comment]
While running the command `bundle exec jekyll serve --incremental` I the local server was not running up while studying the console logs I came to know that the gems are of older version.

As of which I used the command `bundle update` to update the gems and now local website is running in local server.

**Comment by DhairyaMajmudar** [comment]
Shall I open a PR updating the gems in `GemFile.lock` so that such others don't face same problem again.

**Comment by quozl** [comment]
Please give more detail.  The old version should still be available, and should still work.  If an old version does not work, we need to know why rather than just change it blindly.  Why does it fail?

**Comment by quozl** [comment]
Also, please check for regressions; was it an earlier change to Gemfile.lock that caused this?

**Comment by DhairyaMajmudar** [comment]
Here are the console logs.
![image](https://github.com/sugarlabs/www/assets/124715224/ead823e8-d894-48a3-a829-9a9f23c8dc7d)

**Comment by DhairyaMajmudar** [comment]
As of regression, the gemfile.lock was updated last time 17 months ago by #375 but I don't think it is a regression since new gems were added and older ones are not modified.

**Comment by quozl** [comment]
Thanks for the report.  I've updated Jekyll to fix this.  Please pull from master and try again.

2abf6a088c1b1cd0a0308b151d7c035c5d17379d

**Comment by DhairyaMajmudar** [comment]
I was planning to open a PR for that but it's okay you updated it 😅

**Comment by quozl** [comment]
> I was planning to open a PR for that but it's okay you updated it 😅

Please don't open an issue if you are planning to open a pull request.  Just open the pull request instead.  Issues are best used for things you are not going to fix, and hope someone else will fix them.

Please do read https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md

**Comment by DhairyaMajmudar** [comment]
Sure thanks for sharing 😃
