### ISSUE TITLE
Insufficient Content on Website

### ISSUE THREAD

**Issue by AdityyaX** [sugarlabs/www#414]
Description:
Right now, the website doesn't have enough stuff on it. This could make it not work as well and not be interesting for people visiting.

**Comment by quozl** [comment]
I disagree.  There is too much stuff on our web site, and much of it is out of date, having been copied during a previous student project.

**Comment by pikurasa** [comment]
FWIW, I see one of my goals as "answering people's questions".

@AdityyaX would you mind specifying what sorts of things you were expecting to see on the website, that were not there when you looked?

Thanks!
