### ISSUE TITLE
Issue: Implement Dynamic Year in Footer

### ISSUE THREAD

**Issue by AdityyaX** [sugarlabs/www#416]
Currently, the copyright year in the footer of our website requires manual updates every new year. To enhance user experience and alleviate the need for annual adjustments, we propose implementing a dynamic year feature.

**Comment by quozl** [comment]
Please don't open an issue if you are planning to open a pull request. Just open the pull request instead. Issues are best used for things you are not going to fix, and hope someone else will fix them.

You also forgot to link your pull request to the issue.  I shall do that now; https://github.com/sugarlabs/www/pull/417

**Comment by quozl** [comment]
Note the feature must not use the clock of the browser to determine the year; it must be set by the files in the repository.

**Comment by pikurasa** [comment]
We do not plan to implement this.
