### ISSUE TITLE
Local labs broken links

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#418]
These links are currently broken:

- http://co.sugarlabs.org/go/Laboratorios_Az%C3%BAcar_Colombia
- http://cl.sugarlabs.org/go/P%C3%A1gina_Principal
- http://pe.sugarlabs.org/ir/
- http://ar.sugarlabs.org/

These are all linked from https://www.sugarlabs.org/about-us/

What should they be updated to? Or should we just remove them for now?

**Comment by quozl** [comment]
I suggest removing.

**Comment by chimosky** [comment]
> I suggest removing.

I agree.

**Comment by pikurasa** [comment]
Removing the entire section or just the broken links? (If we remove the broken links, it leaves only one link for "Local Labs")

**Comment by sanyamk0** [comment]
> Removing the entire section or just the broken links? (If we remove the broken links, it leaves only one link for "Local Labs")

Hello I am Sanyam a 3rd Year Undergraduate from IIIT Bhopal, India.
I guess it will make sense to remove only broken links and not the link that's working fine.

One more thing ig those broken links are for different countries for translation purpose and better way would be fixing deployment of those links.
(And also can't we just keep a single website for all countries and it will render language according to country site is operated.)

Please correct me if i'm wrong anywhere, I'm new to Open Source and trying to give a valuable contribution to organizations.

**Comment by sanyamk0** [comment]
Also if the links needs to be removed, I would love to contribute to it.
And also in integrating different language to this site dynamically.

**Comment by chimosky** [comment]
> Removing the entire section or just the broken links? (If we remove the broken links, it leaves only one link for "Local Labs")

The link to the DC local lab isn't broken, only thing we need to figure out is if the local lab is active else I don't see a need to have it when it's not active.

Removing the broken links is a good way to go, I don't think we should remove the section as the practice was a good one and we'd like it to continue albeit none of the local labs seem to be running today.

**Comment by chimosky** [comment]
>? One more thing ig those broken links are for different countries for translation purpose and better way would be fixing deployment of those links.
(And also can't we just keep a single website for all countries and it will render language according to country site is operated.)

@sanyamk0 the links won't be fixed as no one is currently maintaining wherever they led to, and the links contained varying info so they can't be kept in a single page and rendered by language.

> Also if the links needs to be removed, I would love to contribute to it.
And also in integrating different language to this site dynamically.

We're leaning towards removing and that's probably what we'll do.
Feel free to integrate different languages to the site dynamically, you can take a look at our [contributing guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md).

**Comment by quozl** [comment]
> Removing the entire section or just the broken links? (If we remove the broken links, it leaves only one link for "Local Labs")

Yes, I agree.  Either.

**Comment by chimosky** [comment]
> @chimosky Okay so I'll start working on the dynamic language translation. Should I Include the removal of the dead links in PR as well??

There's a temporary fix for the issue here [349a340](https://github.com/sugarlabs/www/commit/349a3402fd879871dc78b6bfc2c9f227cd0c3bc5), focusing on one thing in your PR is best.
