### ISSUE TITLE
Add a page for leadership

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#422]
Add a page on who's who, so that people looking at our website knows what's up.

**Comment by soumyaranjan-panda** [comment]
Do you have any preference on how this page should look? And where can I get the details of those who worked on it?

**Comment by pikurasa** [comment]
> Do you have any preference on how this page should look? And where can I get the details of those who worked on it?

I don't have any preference at the moment.

I think the first step is to figure out how to make a new page with Jekyll. If you can provide me with a template, then I can start filling it in with the relevant information.

(This is all pretty new to us, as we haven't really actively maintained the website for a while.)

**Comment by soumyaranjan-panda** [comment]
Hi, would you like an entire page dedicated to it? Take a look at the picture below. We can create something similar with sliding animations.![image](https://github.com/sugarlabs/www/assets/84384924/bb2ecc69-acde-4388-951d-2986eed3c9c8)
If there are too many people, then it's better to dedicate a whole page to it. 
And I learned how to create a new page with Jekyll.

**Comment by soumyaranjan-panda** [comment]
> I think the first step is to figure out how to make a new page with Jekyll. If you can provide me with a template, then I can start filling it in with the relevant information.

# Leaderboard Page Feedback

Hey @pikurasa,

Check this out: [Designs](https://www.figma.com/design/lMruGpoAsCDJBoxu6ryijK/Untitled?node-id=0-1&t=thXxsMkwSthQo30g-1) — this is the leaderboard page. Let me know if you prefer to call it something else or if you have any design suggestions. Feel free to change the design or add comments for any improvements you'd like. If you prefer a different design, let me know and I'll work on it.

### Questions:
- Where can I get the data for all the people working in the organization?
- Does this page include only people working in GitHub, or does it also include those outside the organization?
- Where would you like to place a button or anchor tag on the main page to direct users to this leaderboard page?

Thanks!

**Comment by walterbender** [comment]
The dev community is represented on GitHub. We transferred repos here and the commit logs in theory are intact.

Not sure how to get the contributions to documentation etc. Maybe we can glean data from the wiki?

**Comment by soumyaranjan-panda** [comment]
@walterbender Sir, it can be retrieved using the GitHub API, for example: https://api.github.com/repos/sugarlabs/www/contributors.

**Comment by pikurasa** [comment]
> @walterbender Sir, it can be retrieved using the GitHub API, for example: https://api.github.com/repos/sugarlabs/www/contributors.

I think you can go ahead and give it a try, if you like

**Comment by thefaizwork** [comment]
can i still contribute to this ? i have a good idea - design for this addon leadership page @pikurasa

**Comment by quozl** [comment]
Anyone can contribute.  Here's some ideas;
* write a change and a pull request, containing the leadership team from https://wiki.sugarlabs.org/go/Oversight_Board
* extend the change so that updates to the Wiki are flagged for review somehow,
* review the now unrelated contributors pull request https://github.com/sugarlabs/www/pull/445 using https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#review steps,

**Comment by pikurasa** [comment]
I have a draft of this on https://github.com/pikurasa/www/tree/rehaul

**Comment by pikurasa** [comment]
We now have a leadership page. I just need to figure out a few things in order to improve it a bit, which I can do on a separate ticket.

**Comment by pikurasa** [comment]
@soumyaranjan-panda We may want to replace the current /profiles/ page with your "leaderboard". The profiles page is a little bit out of date. Thoughts?

**Comment by soumyaranjan-panda** [comment]
@pikurasa, Let me gather all the information from our previous work, and I'll share my thoughts on this soon.

**Comment by soumyaranjan-panda** [comment]
# Quick Note

[**chimosky**](https://github.com/chimosky) commented [on Jul 4](https://github.com/sugarlabs/www/pull/445#issuecomment-2209368420)

> I think a page about contributors should be called contributors, although there's already a `profiles.md` which has manual entries, maybe this should replace that or be combined with that as lots of the contributors there didn't write code.

---

[**quozl**](https://github.com/quozl) commented [on Jul 5](https://github.com/sugarlabs/www/pull/445#issuecomment-2209622274)

> I agree, leadership of the organisation does not (and does not need to) correlate to code contribution.

---

**[Oversight Board](https://wiki.sugarlabs.org/go/Oversight_Board)**

---

### My work on contributors page

Fetches the latest data from GitHub and updates the information accordingly.

[**quozl**](https://github.com/quozl) commented [2 weeks ago](https://github.com/sugarlabs/www/pull/445#issuecomment-2388244971)

> But doesn't that make our website critically depend on github.com instead of sugarlabs.org alone? That doesn't seem safe.

**Objective:** We need to hard code it and maintain it.

**Comment by soumyaranjan-panda** [comment]
### My Thoughts

- I think we should make one page for all profiles.
- Create sections to present our members, like:

## The Board for Sugar Labs Inc.

The current board members are:

- [Lionel Laské](https://wiki.sugarlabs.org/go/User:Llaske)
- [Claudia Urrea](https://wiki.sugarlabs.org/go/User:Claudia_Urrea)
- [Samson Goddy](https://wiki.sugarlabs.org/go/User:Samson_Goddy)
- [Walter Bender](https://wiki.sugarlabs.org/go/User:Walter)
- [Alex Perez](https://wiki.sugarlabs.org/go/User:MrBIOS)

## Officers

### **Executive Director**

[Devin Ulibarri](https://wiki.sugarlabs.org/go/User:Pikurasa)

### **Treasurer**

[Claudia Urrea](https://wiki.sugarlabs.org/go/User:Claudia_Urrea)

### **Secretary**

[Walter Bender](https://wiki.sugarlabs.org/go/User:Walter)

## GitHub Contributors

- [Walter Bender](https://wiki.sugarlabs.org/go/User:Walter)
- X
- X

**Comment by pikurasa** [comment]
A leaderboard and a "leadership" page are not the same thing.

I implemented http://www.sugarlabs.org/leadership/ last week. It still needs some updates.

However, we shouldn't put "leaderboard" contributor info on that page.

Instead, I think we can try replacing http://www.sugarlabs.org/profiles/ with the leaderboard that you propose.

**Comment by soumyaranjan-panda** [comment]
So you want a leaderboard page with only GitHub contributors, right?  
I can do that.

But I still think that it would be great to have only one page containing all the members. People have to hop from one page to another for other positions, which is a bit inconvenient.

Let me know your thoughts, and I'll proceed accordingly. If you'd like a demo of how it will look, I can provide that.
