### ISSUE TITLE
Update our documentation on how to update icons (ion icons)

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#436]
We need to update our icons.

I don't know how to do this. This is what I know:

I think there are a batch of files to update. See: https://github.com/sugarlabs/www/commit/932dbab16cb5194ca033edd46448445f908c5526

I /think/ the related code is here: https://github.com/ionic-team/ionicons ; and their homepage is here: https://ionic.io/ionicons

This would help us solve https://github.com/sugarlabs/www/pull/431, as well as just be more up to date in general.

**Comment by soumyaranjan-panda** [comment]
The issue arises from the absence of a Mastodon logo within the Ion-Icons framework we're currently utilizing.

![image](https://github.com/sugarlabs/www/assets/84384924/83155751-8158-4b07-ac4a-47631e5e6eab)
I utilized SVG here. What are your thoughts on it? @pikurasa

**Comment by pikurasa** [comment]
I can see that that works, but isn't there a way to update similarly to what was done with https://github.com/sugarlabs/www/commit/932dbab16cb5194ca033edd46448445f908c5526 with the most current version of that library?

**Comment by pikurasa** [comment]
Perhaps we can use it as a temporary solution.

There is probably some method for "importing" https://github.com/ionic-team/ionicons to our repo.

@nikkuAg are you able to help out with this?

**Comment by nikkuAg** [comment]
Hi,
https://ionic.io/ionicons
You can search for the icon from this page and then just add the icon name in the code

**Comment by soumyaranjan-panda** [comment]
> Hi, https://ionic.io/ionicons You can search for the icon from this page and then just add the icon name in the code

I wish it was that simple, the icons in the codebase are stored locally(which does not include manstodon's icon and has no relation with the site you have given here), so we need to bring them in locally. I did that in #437.

**Comment by nikkuAg** [comment]
> I wish it was that simple, the icons in the codebase are stored locally(which does not include manstodon's icon and has no relation with the site you have given here), so we need to bring them in locally. I did that in #437.

For this you can update the ion package being used and then it will be available in the local folder and then use it

**Comment by pikurasa** [comment]
> > I wish it was that simple, the icons in the codebase are stored locally(which does not include manstodon's icon and has no relation with the site you have given here), so we need to bring them in locally. I did that in #437.
> 
> For this you can update the ion package being used and then it will be available in the local folder and then use it

Can someone here document the steps to update the package, or put a link in our README for where those instructions are? That would really help us in the future.

**Comment by soumyaranjan-panda** [comment]
### How to change/add ion-icons? 
#### 1. Install FontForge:
- Download and install FontForge from [FontForge's official website](https://fontforge.org/en-US/).

#### 2. Create or Prepare Your Icon:
- Create your icon in a vector graphics editor and save it as an SVG file.
- Ensure that your icon is properly scaled and fits well within the boundaries of a single glyph.

#### 3. Open Your .ttf File in FontForge:
- Launch FontForge and open the .ttf file you want to edit by going to `File > Open` and selecting the .ttf file.

#### 4. Add a New Glyph Slot:
- In the FontForge interface, you will see a grid representing different glyphs in the font. Find an empty slot or select an existing glyph that you want to replace.

#### 5. Import Your Icon:
- Double-click on the empty slot or the slot you want to replace to open the glyph editor.
- Go to `File > Import` and select the SVG file of your icon.
- Adjust the size and position of your icon to ensure it fits well within the glyph boundaries.

#### 6. Set the Glyph Properties:
- After importing the icon, you might need to adjust its properties, such as the glyph's width, bearing, and kerning.
- You can do this by using the tools available in the glyph editor.

#### 7. Save Your Changes:
- Once you're satisfied with the new icon, go to `File > Generate Fonts` to save the .ttf file.
- Choose the appropriate options and generate the font file. This will save your .ttf file with the new icon included.

#### 8. Test Your Updated Font:
- Install the updated .ttf file on your system and test it in an application that uses fonts to ensure that your new icon appears correctly.

**Comment by soumyaranjan-panda** [comment]
> ### How to change/add ion-icons?
> #### 1. Install FontForge:
> * Download and install FontForge from [FontForge's official website](https://fontforge.org/en-US/).
> 
> #### 2. Create or Prepare Your Icon:
> * Create your icon in a vector graphics editor and save it as an SVG file.
> * Ensure that your icon is properly scaled and fits well within the boundaries of a single glyph.
> 
> #### 3. Open Your .ttf File in FontForge:
> * Launch FontForge and open the .ttf file you want to edit by going to `File > Open` and selecting the .ttf file.
> 
> #### 4. Add a New Glyph Slot:
> * In the FontForge interface, you will see a grid representing different glyphs in the font. Find an empty slot or select an existing glyph that you want to replace.
> 
> #### 5. Import Your Icon:
> * Double-click on the empty slot or the slot you want to replace to open the glyph editor.
> * Go to `File > Import` and select the SVG file of your icon.
> * Adjust the size and position of your icon to ensure it fits well within the glyph boundaries.
> 
> #### 6. Set the Glyph Properties:
> * After importing the icon, you might need to adjust its properties, such as the glyph's width, bearing, and kerning.
> * You can do this by using the tools available in the glyph editor.
> 
> #### 7. Save Your Changes:
> * Once you're satisfied with the new icon, go to `File > Generate Fonts` to save the .ttf file.
> * Choose the appropriate options and generate the font file. This will save your .ttf file with the new icon included.
> 
> #### 8. Test Your Updated Font:
> * Install the updated .ttf file on your system and test it in an application that uses fonts to ensure that your new icon appears correctly.


Here is a step by step process of updating the package(ion -icons), this is how i updated. I'm unsure if there's a more efficient approach. This method successfully updated the package.

**Comment by pikurasa** [comment]
Our icons were updated (https://github.com/sugarlabs/www/pull/437), but we should also update our documentation as well.
