### ISSUE TITLE
Footer links not visible on mobile

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#439]
Right now footer links are only visible on desktop.

I made a screencast that I can upload, if needed, but you can test by going to www.sugarlabs.org on a phone and scrolling to the bottom.

This is a problem as some of the important links are not displayed on mobile.

**Comment by 404Nikhil** [comment]
Hi @pikurasa, I checked it on my phone. When you click on the subheadings (like Sugar Labs, Development, Resources), the links appear, and all of them are functional. Could you please provide more details about the issue? A screenshot would be helpful.

Also, I noticed that the footer formatting isn't great. There's a 2px on the right side of the footer on the phone. The address and donate message could be arranged in columns for a cleaner look.

**Comment by pikurasa** [comment]
Oh, ok, so you can click on the text to reveal sub-menus as so:


https://github.com/sugarlabs/www/assets/13454579/d30044d2-c001-4400-be4f-f2f061e43eb1

That was not obvious to me, and I worry that others too may miss it.

I wonder if there isn't a way to make it more obvious...

**Comment by pikurasa** [comment]
> Also, I noticed that the footer formatting isn't great. There's a 2px on the right side of the footer on the phone. The address and donate message could be arranged in columns for a cleaner look.

Feel free to offer a solution to this.

**Comment by 404Nikhil** [comment]
ok sure
