### ISSUE TITLE
Be clearer about what is "Sugar" (desktop) and what is "Sugarizer"

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#440]
Many people are getting confused about this, and our website doesn't help.

I can take the lead on this, but wanted to make note of it.

**Comment by priyansh-dubey** [comment]
I want to write an clear description about this , please assign me this issue

**Comment by chimosky** [comment]
We don't assign issues at Sugar Labs, feel free to open a PR and you'll get it reviewed.

**Comment by pikurasa** [comment]
I want to add some images later, but https://www.sugarlabs.org/sugarizer/ is what I meant by this.
