### ISSUE TITLE
Update CSS (without breaking the site)

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#454]
Find simple ways to update CSS without breaking the site.

This is not intended to be a big rehaul of CSS, just a bandaid to get things working "well enough".

**Comment by haroon10725** [comment]
@pikurasa I am working on it.

**Comment by sarthakvyas16** [comment]
I want to fix this issue will you please assign me this issue.

**Comment by chimosky** [comment]
We don't assign issues to anyone, you should look at our [contributing]( Here is the comparison of the updates) docs.

Feel free to open a PR if you have a fix.

**Comment by pikurasa** [comment]
We decided at today's meeting that we won't be doing a wholesale update of the CSS. To join the conversation, you are encouraged to join https://matrix.to/#/#sugarlabs-web:matrix.org
