### ISSUE TITLE
Update ion-icons

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#455]
I believe @soumyaranjan-panda is already working on this, but making a ticket nonetheless.

**Comment by ishwarthecodddr** [comment]
what are ion-icons?

**Comment by pikurasa** [comment]
> what are ion-icons?

I believe they are what are here: https://github.com/ionic-team/ionicons/

**Comment by soumyaranjan-panda** [comment]
@pikurasa Could you please clarify why this issue is still open? Is there anything further we need to address?

**Comment by pikurasa** [comment]
> @pikurasa Could you please clarify why this issue is still open? Is there anything further we need to address?

We seem to be updating them one by one. If we could update the whole library, and link to the instructions for how to do that, then we'd be in a good spot.

**Comment by soumyaranjan-panda** [comment]
The latest versions of Ionicons have moved away from providing font files (which contain .ttf, .woff, and .woff2, which we use in our repo) and instead focus on SVGs and web components(e.g., for React, Next.js). However, if you prefer using the Ionicons as fonts, we can generate them manually using the SVG files from the package with tools like [IcoMoon](https://icomoon.io/app/#/select).

**Comment by dubeanant** [comment]
So @soumyaranjan-panda are u working on this issue? If not pls tell me because I will be glad to take it from here

**Comment by soumyaranjan-panda** [comment]
@dubeanant Go ahead. Let me know if you need any assistance.
