### ISSUE TITLE
update sitemap (easy)

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#457]
Work from master branch and help by updating the sitemap

**Comment by haroon10725** [comment]
@pikurasa I am working on this issue, is there any particular order to follow ?

**Comment by chimosky** [comment]
@pikurasa seems the rehaul branch no longer exists.

> @pikurasa I am working on this issue, is there any particular order to follow ?

There's no particular order to updating the sitemap besides updating it, you could start by figuring out what a sitemap is.

**Comment by pikurasa** [comment]
> @pikurasa seems the rehaul branch no longer exists.

At some point, we decided to just work from the main repo, so I intentionally deleted it.

**Comment by haroon10725** [comment]
@chimosky Sitemap lists all the pages of a website.
