### ISSUE TITLE
Create better layouts for some of our sub-pages

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#458]
Need not be "perfect", but some improvements to the following would be nice:

- Come up with recommendations for better layout for:
- /sugar-stories/
- /2014/01/22/Sugar-Labs(R)-Educational-Nonprofit-Celebrates-Two-Google-Code-In-Grand-Prize-Winners/ etc.
- /parents/ and /school-administrators/ and /students/ (which are all similar)
- /more/

**Comment by ishwarthecodddr** [comment]
assign me this issue

**Comment by omsuneri** [comment]
@ishwarthecodddr we dont assign issues
