### ISSUE TITLE
Replace Sugar Stories table with HTML table

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#466]
On Sugar Stories page, replace /assets/data_table.png with an HTML table

**Comment by omsuneri** [comment]
@pikurasa I ll make it

**Comment by sarthakvyas16** [comment]
I want to work on this issue please assign me this issue.

**Comment by omsuneri** [comment]
@sarthakvyas16 the issue is already solved try to move for another issue

**Comment by sarthakvyas16** [comment]
Ohkay😂
