### ISSUE TITLE
Navbar is not rendering on mobile

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#478]
Currently, Navbar does not seem to be rendering on mobile (tested on Android and Chromium's dev tools).

![Screenshot from 2024-10-13 18-26-32](https://github.com/user-attachments/assets/7ef52d3a-f6cf-4b21-b7ee-cb6614139eff)

I'm not sure when the last time it did work. I remember hearing from someone that something was broken on mobile related to the logo or the navbar, but the logo seems to be rendering.

**Comment by pikurasa** [comment]
_Note: I tried to cleanup the navbar with https://github.com/pikurasa/www/tree/2024-10-13-clean-navbar

This cleans up the code a bit, but does not fix the navbar._

**Comment by haroon10725** [comment]
@pikurasa I am working on it.

**Comment by pikurasa** [comment]
> @pikurasa I am working on it.

How's it going?

I tinkered around with this with @samswag and we found it a bit challenging.

**Comment by therealharshit** [comment]
Is anyone working on this? Or should I take this up

**Comment by haroon10725** [comment]
@therealharshit I am working on it.

**Comment by haroon10725** [comment]
> > @pikurasa I am working on it.
> 
> How's it going?
> 
> I tinkered around with this with @samswag and we found it a bit challenging.

@pikurasa I am cleaning the code to make space for hamburger.

**Comment by therealharshit** [comment]
@pikurasa I have achieved it

Vedio:

https://github.com/user-attachments/assets/abd9ea96-0652-4ca1-b923-8ec30f406b3e

**Comment by haroon10725** [comment]
@pikurasa I have fixed this issue. Now navbar is working fine on all screen sizes.
