### ISSUE TITLE
Add nifty icons to our list on Developers

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#493]
It would be nice to have some icons here:

![Screenshot from 2024-10-17 20-38-49](https://github.com/user-attachments/assets/55412886-6061-4646-bedd-34d6fdbeee63)

Like:
- chat or share icon
- book icon
- mail icon
- language icon
- dev or house icon
- person icon
- people icon

These sorts of fun icons are ion icons, called via CSS (but that's all I know).

**Comment by therealharshit** [comment]
@pikurasa I'll do it.

**Comment by therealharshit** [comment]
@pikurasa  I have made the changes 

![develop](https://github.com/user-attachments/assets/ba9a2799-0d8c-4bf9-8e59-3c9a854c4dbc)


and raised a PR #499 please review.
