### ISSUE TITLE
Add nifty icons to our "contact us" list

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#494]
Add nifty icons to the following, under https://www.sugarlabs.org/contact-us/

![Screenshot from 2024-10-17 20-42-14](https://github.com/user-attachments/assets/bf86ee03-9316-411c-ab5e-bdaf859772f7)

Like:

- house (we have this
- phone
- mail
- chat

These sorts of fun icons are ion icons, called via CSS (but that's all I know).

**Comment by rachelcynthia** [comment]
Hi, can I be assigned to this ?

**Comment by haroon10725** [comment]
@pikurasa I am working on it.

**Comment by haroon10725** [comment]
<img width="761" alt="contact-us" src="https://github.com/user-attachments/assets/6c56951e-03b3-4449-8deb-ae53bf79e262">

**Comment by therealharshit** [comment]
@pikurasa I was also working on this, raised a PR #497 please review.
