### ISSUE TITLE
Carousels are broken

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#521]
It seems that all our carousels are currently broken, which effects things like our testimonial slider (on the front page).

As for as I can tell:
* It worked on dfaa771173282226556e1bb99ab8e0080d51df10
* It stops working on https://github.com/sugarlabs/www/commit/7088c6ddb1b9159eaebd8c8b4138dd83962e55f0

It's more important to have the navbar working than the slider, so if there isn't a quick fix we may opt for a different method of displaying the information.

Here's a screenshot of an inspection of the testimonial slider on the front page:
![Screenshot from 2024-10-26 11-56-05](https://github.com/user-attachments/assets/0225ff9b-9399-4e9e-8b8f-180cbb4cd130)

**Comment by avanshh99** [comment]
Hello there! Please assign me this issue so that i could work on that

**Comment by pikurasa** [comment]
> Hello there! Please assign me this issue so that i could work on that

We don't assign issues, but we do review PRs. Also, we recommend you join us in https://matrix.to/#/#sugarlabs-web:matrix.org, where we are coordinating efforts.

**Comment by Nama21yo** [comment]
@pikurasa Please review my PR #540, which adds a Bootstrap carousel with custom CSS styling. Is there anything that should be improved?

**Comment by therealharshit** [comment]
@pikurasa i have fixed it and raised a PR #541 please review.
