### ISSUE TITLE
Put boiler plate "about Sugar Labs" text into a _includes html

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#534]
We're going to want to stamp a boiler plate "about Sugar Labs" text on many pages, such as our press releases.

We can copy and paste manually, or we can put the text into _includes as html that we can use again and again. The benefit of doing the latter is that it will be easy to update if we ever decide to make some changes.

Our current text is as follows:
```
## About Sugar Labs

Sugar Labs® is a US-based 501(c)(3) nonprofit organization with a
global mission to create educational opportunities in technology to
youth around the world. Volunteer mentors and contributors work
together to develop activity-focused software for children. All
software is developed with learning as the primary goal, necessitating
the need for source code to be published publicly for study, licensed
under a free/libre license for explicit permission to share and remix,
and openly worked upon within a community where students are invited
to make contributions, under guidance of experienced mentors.
Donations to support the work of Sugar Labs can be made at
<https://www.sugarlabs.org/donate/>.
```

**Comment by nischal-shetty2** [comment]
Hey, I would love to work on this! I’m new to this repo, so I’m not sure if we need to be officially assigned to an issue before working on it, @pikurasa . in the meantime, I’ll go ahead and create a PR for this.
