### ISSUE TITLE
Font size is not readable on mobile phone

### ISSUE THREAD

**Issue by aneesmalikdev** [sugarlabs/www#544]
![image](https://github.com/user-attachments/assets/80d69b61-39f1-4fa7-ac57-5aa316453617)

**Comment by aneesmalikdev** [comment]
I am working on this.

**Comment by omsuneri** [comment]
we guyss are doing this for the mobile version and soon will get it done just keep patience @aneesmalikdev

**Comment by aditya270520** [comment]
please assign this issue to me i can resolve this
Font size is not readable on mobile phone #544

**Comment by quozl** [comment]
Sorry, I don't understand.  Why can't you fix it without assignment?  You are asking for the right to be the only one to fix it?  We can't offer that right.  Anyone could fix it.

**Comment by quozl** [comment]
I've opened sugarlabs.org on mobile, and the text size is fine at the moment.  Presumably some of the recent commits have fixed it without closing the issue.
