### ISSUE TITLE
Minor Home Page Typo

### ISSUE THREAD

**Issue by mohanamisra** [sugarlabs/www#547]
I've noticed a small typo on the homepage, where "communinity" is written instead of "community."

While this is a minor issue, correcting it could help maintain the project’s professional appearance in terms of content, especially for uninitiated users. I’d be happy to make this correction if that’s helpful!

![image](https://github.com/user-attachments/assets/1aa2f0ba-1be3-425d-830b-75ec43eec05a)

**Comment by quozl** [comment]
Please don't create issues for full requests that you are about to create.  Just create the pull request.

**Comment by mohanamisra** [comment]
> Please don't create issues for full requests that you are about to create. Just create the pull request.

Will do !
