### ISSUE TITLE
Add author name to blogs

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#571]
I'm not super-familar with Jekyll, but I suspect that we can put the following into the front matter and have it display in our posts:

`author: "Author Name"`

It would then put "by Author Name" underneath the title of the page.

**Comment by Manav958** [comment]
Hi @pikurasa Could you elaborate more about this?

**Comment by Devmoni** [comment]
@pikurasa can you please explain more about the issue?

**Comment by pikurasa** [comment]
> @pikurasa can you please explain more about the issue?

I suspect there is a way to input the author name into the "front matter" (the meta stuff at the beginning of the markdown file for these blogs) and have it display in the generated html, just like the title and the date are generated.

I'm asking for someone to look into this.

**Comment by Devmoni** [comment]
I really appreciate your explanation. Thank you!

**Comment by LakshayPuhal** [comment]
Hey , i would like to work on this issue

**Comment by quozl** [comment]
Thanks.  But please don't ask, just do.  Unless you have questions about the issue itself, the next thing we expect is a pull request.  We do not approve exclusivity in work.

**Comment by vidipsingh** [comment]
@pikurasa @quozl
I have made a PR that solves this issue by adding the author name display below the blog title. The author name is now dynamically fetched from the front matter and displayed as "by Author Name." 

Please review the [PR](https://github.com/sugarlabs/www/pull/614) and let me know if there are any changes required.
