### ISSUE TITLE
The text is not visible due to navbar 

### ISSUE THREAD

**Issue by sahiladit** [sugarlabs/www#574]
The image below the navbar is not completely visible , place the image slightly low or decrease the size of the navbar.

<img width="1440" alt="Screenshot 2024-12-06 at 9 05 31 AM" src="https://github.com/user-attachments/assets/151c0e88-8324-45a5-9567-65e46ebacacd">

**Comment by Srishti-Chugh** [comment]
Hi! I'm interested in helping with the navbar issue and have a solution in mind that will adjust the spacing for better visibility. Could I be assigned to this issue?

**Comment by quozl** [comment]
Welcome. It appears there may be some confusion regarding the process of addressing issues. It is important to understand that the ability to resolve a problem is not restricted to a single individual. The notion of exclusivity in fixing an issue is not feasible, as it can be addressed by anyone—be it yourself, another individual, or a collaborative group.

**Comment by AetherSparks** [comment]
Srishti, Your Commit only works in full screen Desktop, it is still hiding the text when Dimensions are changed. I have applied a Dynamic Approach, which fixes this issue in real-time as you change dimensions.

**Comment by sahiladit** [comment]
> Srishti, Your Commit only works in full screen Desktop, it is still hiding the text when Dimensions are changed. I have applied a Dynamic Approach, which fixes this issue in real-time as you change dimensions.

i think we should give size/length in %

**Comment by quozl** [comment]
> Srishti, Your Commit only works in full screen Desktop, it is still hiding the text when Dimensions are changed. I have applied a Dynamic Approach, which fixes this issue in real-time as you change dimensions.

Please review commits in the pull request, so that everyone else who is reviewing sees what you write.  I don't think issues are the best place to discuss how to solve an issue.

(If you've decided to collaborate with another person, create a draft empty pull request, then enable push permissions to your fork and you can both push commits to the pull request branch.)

**Comment by haroon10725** [comment]
@pikurasa We should also close this issue, as it is fixed.
https://github.com/sugarlabs/www/pull/603#issuecomment-2561231442

**Comment by quozl** [comment]
Agreed.
