### ISSUE TITLE
NavBar buttons text gets covered up when it is minimized

### ISSUE THREAD

**Issue by AetherSparks** [sugarlabs/www#575]
### Description
Apart from issue #574 raised by sahiladit, where the navbar is hiding the text behind, I have noticed that the buttons in the navbar itself are glitchy.

Apart from the weirl L shaped nav buttons visible when you click them, when you scroll down a weird white circle covers a part of the text in the About and News buttons.

### Expected Behavior
The Text in the Navbar buttons should not be hidden, the Button itself should be fixed to a square/rectangle button, pushing the arrow up.
Also the navbar shouldnt be hiding any text behind it.

### Screenshots

https://github.com/user-attachments/assets/eac7f112-1f45-4f79-b86a-dc96c680d149

### How to Reproduce
Just scroll down and click any of the navbar buttons

### Environment:

-   Operating System: Windows
-   Browser (if applicable): Chrome

### Checklist

-   [x] I have read and followed the project's code of conduct.
-   [x] I have searched for similar issues before creating this one.
-   [x] I have provided all the necessary information to understand and reproduce the issue.
-   [x] I am willing to contribute to the resolution of this issue.

**Comment by sahiladit** [comment]
@AetherSparks are you working on this issue?

**Comment by AetherSparks** [comment]
@sahiladit Yes I am. Would You Like to Collaborate?

**Comment by sahiladit** [comment]
> @sahiladit Yes I am. Would You Like to Collaborate?
> 

Yes 👍🏻

**Comment by AetherSparks** [comment]
> > @sahiladit Yes I am. Would You Like to Collaborate?
> 
> Yes 👍🏻

Ping a Message in Element so we can collaborate further. Also can you tell me which version of Ruby are you using? I am getting a function deprecation error.

**Comment by sahiladit** [comment]
> > > @sahiladit Yes I am. Would You Like to Collaborate?
> > 
> > 
> > Yes 👍🏻
> 
> Ping a Message in Element so we can collaborate further. Also can you tell me which version of Ruby are you using? I am getting a function deprecation error.

3.3.6 the latest one

**Comment by Sparsh-3011** [comment]
anyone working on the issue i would like to collab?

**Comment by haroon10725** [comment]
@pikurasa We should also close this issue, as it is fixed.
https://github.com/sugarlabs/www/pull/603#issuecomment-2561231442

**Comment by quozl** [comment]
Yes, is fixed.
