### ISSUE TITLE
We need to update our mission blurb

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#576]
This is on our front page:

[Sugar Labs®](https://wiki.sugarlabs.org/go/Trademark) is a volunteer-driven member project of a nonprofit corporation. Originally part of the One Laptop Per Child project, Sugar Labs coordinates [volunteers](https://wiki.sugarlabs.org/go/Sugar_Labs/Getting_Involved) around the world who are passionate about providing educational opportunities to children through the Sugar Learning Platform. Sugar Labs® is supported by donations and is seeking [funding](https://wiki.sugarlabs.org/go/Sugar_Labs/Donate) to accelerate development.

I didn't see it until just now, but we are no longer a "member project of a nonprofit corporation".

I will assign myself, but I wanted to make this note of it as to not forget.

**Comment by MostlyKIGuess** [comment]
@pikurasa , 
![image](https://github.com/user-attachments/assets/fc685721-b317-4768-bc9c-d43319c28053)


Does the line 
> “Sugar Labs” is a registered USA 501(c)(3) tax-exempt, not-for-profit organization, which serves as a support base and gathering place for the community of educators and software developers who want to extend the platform and who have been creating Sugar-compatible applications.


Still hold true, if not ,what should we change it to?

**Comment by quozl** [comment]
@pikurasa has this in hand, so not discussing.

**Comment by pikurasa** [comment]
> Still hold true, if not ,what should we change it to?

Mainly the issue had to do with the text stating that we were a member of another nonprofit org. We are now our own nonprofit org.

I did make a mistake in this ticket by saying it was on the front page. The text was on the about us page.

I have resolved it.

Thanks for looking into it!
