### ISSUE TITLE
Make a better banner for fundraisers

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#579]
What I implemented for our website is just an emergency fix for a banner.

I basically just shoved a blurb and paypal link into our current navbar. It looks like this:

![Screenshot from 2024-12-11 09-30-52](https://github.com/user-attachments/assets/b4c44d1d-82bc-4a26-8b7b-574cdbbb446c)

Code: https://github.com/sugarlabs/www/blob/master/_includes/nav.html

However, a more robust and elegant solution would be to put a real banner at the top of the page, independent of the navbar. During non-fundraiser seasons, we can comment it out (or just not call it, if we give it a dedicated file).

**Comment by haroon10725** [comment]
@pikurasa I am working on it.

**Comment by satyam-code45** [comment]
@pikurasa I’ve been trying to resolve the issue by rendering a new banner section above the header. However, when I attempted to implement the change and place the banner above the nav.html file, it did not reflect on the site.

To investigate where the rendering of the header/navbar is happening, I tried disabling it by commenting out the {% include nav.html %} line in both index.html and the default.html layout files. Despite these changes, the navbar continues to render as usual. I’ve also confirmed that the navbar is not hardcoded into individual pages or other obvious templates.

Could you please help clarify from where the actual rendering of the navbar is happening? Is there some JavaScript, plugin, or alternative template that might be dynamically including the header? Identifying the source would greatly help in implementing the required changes.

**Comment by abhassen44** [comment]
![Screenshot 2024-12-13 200515](https://github.com/user-attachments/assets/79e18a29-9664-4817-80b3-79a4e1beeca1)
i make it like this is this ok 
or something else i have to do

**Comment by bhagyashree980** [comment]
hii @pikurasa ,i Updated the _includes/nav.html file to include:
A new banner for larger screens (banner.html).
A responsive banner for smaller screens (banner-mobile.html).
make some changes banner for fundraisers

**Comment by Devmoni** [comment]
https://github.com/user-attachments/assets/f2197b98-0536-4123-997e-435eebe03ad8

@pikurasa Does this method work well according to you? or Would you like any more refinements?

**Comment by Devmoni** [comment]
Due to the recent merge of #582 into the master branch, the banner now hides under the navbar on the desktop website. On other devices, the main problem still persists.
@pikurasa 

### Screenshot

![image](https://github.com/user-attachments/assets/cc804a0c-8e33-45ab-a6d9-f42840fea315)

**Comment by Devmoni** [comment]
> vide0.mp4 
> @pikurasa Does this method work well according to you? or Would you like any more refinements?

This could be one of the methods to solve the problem across all devices.
