### ISSUE TITLE
Link to our Bonfire Merch store

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/www#580]
It would be nice to have a section dedicated to our clothing merch from the first page, and possible linked from the navbar (either its own top-menu or under "donate").

Here's the link to our store: https://www.bonfire.com/store/sugar-labs-merch/

**Comment by therealharshit** [comment]
@pikurasa I'll do this.

**Comment by therealharshit** [comment]
Hey @bhagyashree980 we don't assign issue, and this issue has been resolved in #581.
If you want you can work on other open issues.

**Comment by bhagyashree980** [comment]
Thank you for the update @therealharshit 
Are there any beginner-friendly issues or tasks I can work on to get started with contributing?

**Comment by pikurasa** [comment]
@bhagyashree980 Harshit is correct that we don't assign issues.

That said, the one part of this issue that we could still implement is a section on the front page that tells visitors that they can purchase Sugar Labs merch in our store, all while supporting the organization.

**Comment by therealharshit** [comment]
> @bhagyashree980 Harshit is correct that we don't assign issues.
> 
> That said, the one part of this issue that we could still implement is a section on the front page that tells visitors that they can purchase Sugar Labs merch in our store, all while supporting the organization.

@bhagyashree980 you can also join https://matrix.to/#/#sugarlabs-web:matrix.org for any further discussion.

**Comment by bhagyashree980** [comment]
Thanks  @pikurasa @therealharshit  for the suggestion! I’d be happy to work on adding a section to the front page that informs visitors about the Sugar Labs merch store and how it supports the organization. I’ll create a PR for this soon.
