### ISSUE TITLE
Enhancement for service section

### ISSUE THREAD

**Issue by Devmoni** [sugarlabs/www#584]
### Description:

The visual appearance and responsiveness of the SVG icons in the service item section on website need to be enhance.

### Screenshot:

![image](https://github.com/user-attachments/assets/1c20517d-66f6-4538-a277-c8ac98ab815a)

### Steps to Reproduce:

Open the webpage where the service item SVG icons are displayed.

### Are You Working on this issue:
Yes

**Comment by quozl** [comment]
Good, you're working on it, go ahead and make a pull request.  We don't need issues for things someone is working on, it's just a waste of notifications, so I'll close the issue.
