### ISSUE TITLE
Enhance Developer Setup by Creating a Docker Image for Easy Server Deployment

### ISSUE THREAD

**Issue by MostlyKIGuess** [sugarlabs/www#601]
## Description
Setting up and running a server for development using Jekyll and Bundler can be challenging for new contributors due to the required dependencies and configurations. To simplify the process and make the project more accessible, a Docker image should be created to streamline the setup.

## Benefits
- Simplifies the setup process for new developers.
- Reduces dependency issues by encapsulating the environment.
- Makes contributing to the project easier and more efficient.

## Additional Notes
This enhancement will provide a robust, standardized setup process for all developers.

**Comment by quozl** [comment]
Before reviewing the pull request, I'd like to hear if any other developers plan to use this?  i.e. let's get consensus on the issue.  I think it unnecessarily hides configuration detail and is unlike how the web site is deployed.  It also creates a development dependency on Docker Compose for those who wish to use the feature.  It also won't be for all developers as claimed.

**Comment by MostlyKIGuess** [comment]
> Before reviewing the pull request, I'd like to hear if any other developers plan to use this?  i.e. let's get consensus on the issue.  I think it unnecessarily hides configuration detail and is unlike how the web site is deployed.  It also creates a development dependency on Docker Compose for those who wish to use the feature.  It also won't be for all developers as claimed.

I think we can still deploy as before, but for the development part it makes it easier for someone entering new to just docker compose up and start working with the codebase. That was the initial idea. 

And further if we ever decide to scale up from GitHub deployment we could easily deploy as docker would be the easiest option to transfer.

**Comment by Vishvsalvi** [comment]
If the website is handling complex backend or multiple services then it makes sense to containerize the website. If not then keep it as it is.

**Comment by quozl** [comment]
Thanks.  We're not deploying with a container ourselves, we're using conventional GitHub hosting and they use a container of their own design.  There's no backend complexity or services; once deployed it is static serving.

@pikurasa what do you think, how much time are we wasting helping new contributors overcome their difficulty in learning Jekyll or Gems, and would we rather be helping them learn Docker?  :grin:

**Comment by pikurasa** [comment]
I currently don't understand Docker very well.

I kind of worry that going down this road causes more complexity, even though I understand that some folks are having issues.

For a larger, more complex project like Sugarizer or Music Blocks, I think containers makes more sense; that the effort to containerize is worth the trouble. But for the website, I'm not yet persuaded.

**Comment by quozl** [comment]
Thanks.

@MostlyKIGuess perhaps make sure README.md accurately portrays what is required for new developers?  The file was once a GSoC submission summary, and may need more work.
